# Generated by Django 4.1.1 on 2022-09-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_bool',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
