# Generated by Django 4.1.4 on 2023-01-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_my_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_bool',
            field=models.BooleanField(default='False', verbose_name='We use cookie on this site. I understand'),
        ),
    ]
