# Generated by Django 4.1.4 on 2022-12-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Unique name')),
                ('title', models.CharField(max_length=120, verbose_name='Course name')),
                ('desc', models.TextField(verbose_name='About course')),
                ('image', models.ImageField(default='default.png', upload_to='course_images', verbose_name='Iamge')),
            ],
        ),
    ]
